### ISSUE TITLE
Viết tài liệu

### ISSUE THREAD

**Issue by Trong1102** [Trong1102/Machine_Translation-en-vi#4]
Viết tài liệu về Dịch máy gồm các mục:
- xử lí dữ liệu tiếng việt, tiếng anh
- Mô hình dịch máy transfomer: các lớp encode, decode, self-attention, phương pháp beam-search và các mục liên quan
- tìm thêm bài báo liên quan 
- Tóm tắt nội dung vào file readme.md

**Comment by quantienquanz** [comment]
.
